# Generated by Django 4.0.4 on 2022-05-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.TextField(max_length=50)),
                ('direccion', models.TextField()),
                ('cuit', models.TextField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=14)),
                ('fecha_registro', models.DateField()),
            ],
        ),
    ]
